Repository GeoscienceAustralia/dea-notebooks, pull requests merged in 2020-04, with the labels that each got.

#540 Fix #539 by simplifying multiple z-value, single array mode in `subpixel_contours`
  Scripts/dea_spatialtools.py
Labels: bug

#537 Fix possible bug in subpixel_contours
  Scripts/dea_spatialtools.py
Labels: bug

#542 Change basemap for filmstrips notebook
  Real_world_examples/Change_filmstrips.ipynb
  Scripts/notebookapp_changefilmstrips.py
Labels: new feature/enhancement

#549 improve `xr_rasterize`
  Frequently_used_code/Rasterize_vectorize.ipynb
  Scripts/dea_spatialtools.py
Labels: new feature/enhancement

#553 Fix TSmask notebook to work with new flags
  DEA_datasets/TSmask.ipynb
Labels: bug

#558 Fix dask dashboard link
  Scripts/dea_dask.py
Labels: bug

#562 Update README.rst
  README.rst
Labels: assistance-requested

#564 Update segmentation notebook to fix incorrect header and reduce load …
  Frequently_used_code/Image_segmentation.ipynb
Labels: bug
