Repository GeoscienceAustralia/dea-notebooks, pull requests merged in 2020-10, with the labels that each got.

#627 Add git commands for checking out a branch during a PR review
  README.rst
Labels: documentation

#660 Add notebook demonstrating reprojection using geoboxes
  Frequently_used_code/README.rst
  Frequently_used_code/Reprojecting_data.ipynb
  Supplementary_data/Reprojecting_data/canberra_dem_250m.tif
Labels: new feature/enhancement

#680 Added coastal waterbodies extraction notebook
  Scientific_workflows/DEAWaterbodies/CoastalWaterbodies/ExtractingCoastalWaterbodies.ipynb
Labels: Hacktoberfest

#682 Fix formatting issues with PCA notebook
  Frequently_used_code/Principal_component_analysis.ipynb
Labels: bug
